### PR TITLE
MindBody prototype help

### PR DESCRIPTION
**Pull request by SergiiShapoval**

### CODE REVIEW

**Comment by SergiiShapoval** [comment]
I think we can discuss here, do you receive notifications on these comments?

**Comment by highsource** [comment]
Yes I do. I'd just prefer an open issue (which I could close after it is resolved).

**Comment by SergiiShapoval** [comment]
ok, opened, sorry - my first issue and stackoverflow post :) https://github.com/highsource/hyperjaxb3-support/issues/2

**Comment by highsource** [comment]
No problem, you're doing good.

**Pull request merged**
