### PR TITLE
Support for railML 2.2 import

### PR DESCRIPTION
**Pull request by S-Man42**
Hi
thanks for your offer to support me.

I read your advice to make it a minimum example. But I am not quiet sure which components are relevant or not. It is possible to try the converting with one of the subschemas as rollingstock.xsd. But this one has also its dependencies.

I tried several approaches. I couldn't get the wildcards ignored. So I deleted them manually from all schema files. But this leads to other problems. I think the final most problematic file is the genericRailML.xsd. So I cannot decide which level is the most minimal.

So I am not sure whether it is really possible to get a JPA model from such a huge XSD schema.

I really really thank you for your offer. If you have any questions please let me know.

Kind regards,
Mark

### CODE REVIEW

**Comment by S-Man42** [comment]
Thank you. This example is the unmodified railML2.2 schema with all wildcards included.

**Comment by highsource** [comment]
OK, good to know. I'll come to this next week earliest, sorry.

**Comment by S-Man42** [comment]
No problem. Don't want you to be in hurry! :-)

**Comment by S-Man42** [comment]
Hi, do you have any news? :)

**Comment by highsource** [comment]
Sorry, not yet. I was in a hospital last week.

**Comment by S-Man42** [comment]
Oh I am sorry. Get well soon!

**Comment by highsource** [comment]
I've commented out a few items, at least it compiles now.
Roundtrip does not work yet though. No idea why.

**Comment by highsource** [comment]
You'll get around 400 tables by the way.

**Comment by S-Man42** [comment]
Hi, thanks. Is this just working with your snapshot 0.6.3 version? with Maven Central's 0.6.2 I am getting an error:

```
java.lang.NullPointerException
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.ref(DefaultGetTypes.java:42)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process(DefaultGetTypes.java:29)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process(DefaultGetTypes.java:25)
        at org.jvnet.hyperjaxb3.ejb.strategy.ignoring.impl.DefaultIgnoring.isPropertyInfoIgnored(DefaultIgnoring.java:175)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process(DefaultProcessPropertyInfos.java:96)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process(DefaultProcessPropertyInfos.java:28)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process(DefaultProcessClassInfo.java:17)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process(DefaultProcessClassInfo.java:12)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process(DefaultProcessModel.java:51)
        at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process(DefaultProcessModel.java:32)
        at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process(DefaultModelAndOutlineProcessor.java:43)
        at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process(DefaultModelAndOutlineProcessor.java:16)
        at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.run(EjbPlugin.java:213)
        at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run(AbstractPlugin.java:52)
        at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
        at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
        at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Error while generating code.Location [].
org.xml.sax.SAXParseException: Error during plugin execution.
    at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run (AbstractPlugin.java:54)
    at com.sun.tools.xjc.model.Model.generateCode (Model.java:292)
    at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode (XJC22Mojo.java:66)
    at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute (XJC22Mojo.java:41)
    at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute (XJC22Mojo.java:28)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute (RawXJC2Mojo.java:505)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute (RawXJC2Mojo.java:328)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.NullPointerException
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.ref (DefaultGetTypes.java:42)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process (DefaultGetTypes.java:29)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultGetTypes.process (DefaultGetTypes.java:25)
    at org.jvnet.hyperjaxb3.ejb.strategy.ignoring.impl.DefaultIgnoring.isPropertyInfoIgnored (DefaultIgnoring.java:175)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process (DefaultProcessPropertyInfos.java:96)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessPropertyInfos.process (DefaultProcessPropertyInfos.java:28)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process (DefaultProcessClassInfo.java:17)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessClassInfo.process (DefaultProcessClassInfo.java:12)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process (DefaultProcessModel.java:51)
    at org.jvnet.hyperjaxb3.ejb.strategy.model.base.DefaultProcessModel.process (DefaultProcessModel.java:32)
    at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process (DefaultModelAndOutlineProcessor.java:43)
    at org.jvnet.hyperjaxb3.ejb.strategy.processor.DefaultModelAndOutlineProcessor.process (DefaultModelAndOutlineProcessor.java:16)
    at org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin.run (EjbPlugin.java:213)
    at org.jvnet.jaxb2_commons.plugin.AbstractPlugin.run (AbstractPlugin.java:52)
    at com.sun.tools.xjc.model.Model.generateCode (Model.java:292)
    at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode (XJC22Mojo.java:66)
    at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute (XJC22Mojo.java:41)
    at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute (XJC22Mojo.java:28)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute (RawXJC2Mojo.java:505)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute (RawXJC2Mojo.java:328)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by S-Man42** [comment]
Thanks a lot for your help. Really great!

The snapshot works for class generation. But it does not pass the test (using Postgres; Error: wrong value for field millisecond: -120; I didn't find this value anywhere in the file). Is this working for you?

Nevertheless I took the generated classes. The unmarshalling works pretty fine. 
```
	private Railml railml;

	protected void unmarshall() throws JAXBException {
		final Unmarshaller unmarshaller = context.createUnmarshaller();
		final Object object = unmarshaller.unmarshal(new File("src/test/samples/Ostsachsen_V220-i4 Stand V225-75.xml"));

		railml = ((Railml) object);
	}

	protected void persistToDB() {
		final EntityManager saveManager = entityManagerFactory.createEntityManager();
		saveManager.getTransaction().begin();
		saveManager.persist(railml);
		saveManager.getTransaction().commit();
		saveManager.close();

		System.out.println(railml.getHjid());
	}
```
The persisting does not work (Error: value too long for character varying(255)). I changed every appearance of` length = 255` to `length = 8000` but error stays with 8000). There seems to be an wrong parsed object at some point. Is it possible to visualize the problematic object?

**Comment by highsource** [comment]
> Roundtrip does not work yet though. No idea why.

No, it does not work for me. I did not get to this point at all (tried testing with HSQLDB).

**Comment by highsource** [comment]
@S-Man42 Before I invest more time in this, please check the created database schema and make sure this is what you want. I really don't think it's the right approach for such a big schema. Think about queries, how many joins you'll need.

**Comment by S-Man42** [comment]
Hi, I tried different database management systems but I still get stucked at the same point: roundtrip test fails or strange errors on field values. I will try to debug the code but maybe you will have any additional ideas?

**Comment by S-Man42** [comment]
There is a problem with referenced object. 
<railml>
    <infrastructure id = "abc"> ... </infrastructure>
    <rollingstock infrastructureRef = "abc"> ... </rollingstock>
</railml>

Instead of adding the IDs to infrastructureRef you are adding the whole infrastructure object. Furthermore I think it is not just the origin object but a copy because the code marshals it every time the reference occurs

**Pull request merged**
